print("Olá programador!")
nome = input("Digite o nome: ")
ano = int(input("Digite o ano de nascimento: "))
idade = int(2019 - ano)
print("seu nome é " + str(nome) + " e você tem " + str(idade) + " anos")
