n1 = float(input("informe a nota do primeiro bimestre: "))
n2 = float(input("informe a nota do segundo bimestre: "))
n3 = float(input("informe a nota do terceiro bimestre: "))
n4 = float(input("informe a nota do quarto bimestre: "))
p1 = float(input("informe o peso da nota do primeiro bimestre: "))
p2 = float(input("informe o peso da nota do segundo bimestre: "))
p3 = float(input("informe o peso da nota do terceiro bimestre: "))
p4 = float(input("informe o peso da nota do quarto bimestre: "))
p5 = (n1 * p1 + n2 * p2 + n3 * p3 + n4 * p4) / (p1 + p2 + p3 + p4)
print("a media total eh: " + str(p5) )
