print("**programa gerador de tabuada **")
n = int(input(" informe o numero + ':"))
print(str(n) + ' x 1 = '+ str(1*n))
print(str(n) + ' x 2 = '+ str(2*n))
print(str(n) + ' x 3 = '+ str(3*n))
print(str(n) + ' x 4 = '+ str(4*n))
print(str(n) + ' x 5 = '+ str(5*n))
print(str(n) + ' x 6 = '+ str(6*n))
print(str(n) + ' x 7 = '+ str(7*n))
print(str(n) + ' x 8 = '+ str(8*n))
print(str(n) + ' x 9 = '+ str(9*n))
print(str(n) + ' x 10 = '+ str(10*n))

